name: ci
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  CARGO_INCREMENTAL: 0

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check --all

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace --bins --examples --tests --benches --all-targets --all-features

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --bins --examples --tests --benches --all-targets --all-features --no-fail-fast

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: clippy
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --bins --examples --tests --benches --all-targets --all-features

  doc:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace --bins --examples --all-features --no-deps
